// <auto-generated />
using API_Labb3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Labb3.Migrations
{
    [DbContext(typeof(PersonInterestDbContext))]
    partial class PersonInterestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Labb3.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Volleyball"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Taking pictures with either an old or a new camera",
                            Title = "Photograph"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Both computer and vidio games",
                            Title = "Gaming"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Back and white peices",
                            Title = "Chess"
                        },
                        new
                        {
                            Id = 5,
                            Description = "All kind of programming",
                            Title = "Programming"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Specificly with oilpaint",
                            Title = "Painting"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Outside climbing on big and steep mountains",
                            Title = "Climing"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Somewhere, anywhere",
                            Title = "Hiking"
                        });
                });

            modelBuilder.Entity("API_Labb3.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("PersonInterestId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonInterestId = 0,
                            URL = "www.google.se"
                        },
                        new
                        {
                            Id = 2,
                            PersonInterestId = 0,
                            URL = "www.medium.com"
                        },
                        new
                        {
                            Id = 3,
                            PersonInterestId = 0,
                            URL = "www.youtube.com"
                        },
                        new
                        {
                            Id = 4,
                            PersonInterestId = 1,
                            URL = "www.trail.com"
                        },
                        new
                        {
                            Id = 5,
                            PersonInterestId = 0,
                            URL = "www.chess.com"
                        });
                });

            modelBuilder.Entity("API_Labb3.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 16,
                            Firstname = "Fibie",
                            Lastname = "MeowMoew",
                            Phone = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 27,
                            Firstname = "Herman",
                            Lastname = "Axelsson",
                            Phone = 0
                        },
                        new
                        {
                            Id = 3,
                            Age = 78,
                            Firstname = "Nalle",
                            Lastname = "Pugh",
                            Phone = 0
                        },
                        new
                        {
                            Id = 4,
                            Age = 10,
                            Firstname = "Holly",
                            Lastname = "WoofWoof",
                            Phone = 0
                        },
                        new
                        {
                            Id = 5,
                            Age = 17,
                            Firstname = "Rosa",
                            Lastname = "FierceKitty",
                            Phone = 0
                        });
                });

            modelBuilder.Entity("API_Labb3.Models.PersonInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestID")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestID");

                    b.HasIndex("PersonID");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestID = 8,
                            PersonID = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestID = 3,
                            PersonID = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestID = 5,
                            PersonID = 1
                        },
                        new
                        {
                            Id = 4,
                            InterestID = 8,
                            PersonID = 2
                        },
                        new
                        {
                            Id = 5,
                            InterestID = 7,
                            PersonID = 2
                        });
                });

            modelBuilder.Entity("API_Labb3.Models.Link", b =>
                {
                    b.HasOne("API_Labb3.Models.PersonInterest", "PersonInterests")
                        .WithMany("Links")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("API_Labb3.Models.PersonInterest", b =>
                {
                    b.HasOne("API_Labb3.Models.Interest", "Interests")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Labb3.Models.Person", "Persons")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interests");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("API_Labb3.Models.Interest", b =>
                {
                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("API_Labb3.Models.Person", b =>
                {
                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("API_Labb3.Models.PersonInterest", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
